### ISSUE TITLE
scVI -> scANVI "RuntimeError: mat1 and mat2 shapes cannot be multiplied" 

### ISSUE THREAD

**Issue by davemcg** [scverse/scvi-tools#1450]
# Hello All
Misshapen matrices for scANVI. Read below for how I "solved" it (tldr can't use a continuous_covariate in the `scvi.model.SCVI.setup_anndata` step.

# scvitools Version
```
>>> scvi.__version__
'0.15.2'
```

# Reproducible example
```python
adata = sc.read(
    "data/scEiaD_mini.h5ad",
    backup_url="https://hpc.nih.gov/~mcgaugheyd/scEiaD/2021_11_11/scEiaD_all_anndata_mini_ref.h5ad",
)
adata.X = sparse.csr_matrix(adata.X)
adata.raw = adata  
sc.pp.highly_variable_genes(
    adata,
    flavor="seurat_v3",
    n_top_genes=2000,
    batch_key="study_accession",
    subset=True
)

scvi.model.SCVI.setup_anndata(adata, batch_key='study_accession', continuous_covariate_keys = ['percent.mt'])

arches_params = dict(
    use_layer_norm="both",
    use_batch_norm="none",
    encode_covariates=True,
    dropout_rate=0.2,
    n_layers=2,
    n_latent = 15,
)

vae = scvi.model.SCVI(
    adata,
    **arches_params
)

vae.train(max_epochs = 20)


lvae = scvi.model.SCANVI.from_scvi_model(
    vae,
    adata=adata,
    labels_key="CellType",
    unlabeled_category="NA",
)
lvae.train(max_epochs=5)
```
# CellType composition
```
>>> adata.obs['CellType'].value_counts()
NA                         17192
Rod                         5097
Fibroblast                  4991
Muller Glia                 4470
Retinal Ganglion Cell       3044
Amacrine Cell               1944
T/NK-Cell                   1670
B-Cell                      1492
Schwann                     1434
Bipolar Cell                1349
Macrophage                  1066
Pericyte                     787
Blood Vessel                 758
Melanocyte                   756
RPC                          722
Smooth Muscle Cell           484
Endothelial                  461
Monocyte                     298
Horizontal Cell              267
Microglia                    263
Cone                         223
Choriocapillaris             223
Astrocyte                    202
Neurogenic Cell               82
Red Blood Cell                79
Photoreceptor Precursor       77
Mast                          69
AC/HC_Precursor               66
RPE                           58
Rod Bipolar Cell              48
Name: CellType, dtype: int64
```

# Error return on running `lvae.train()`
```pytb
>>> lvae.train(max_epochs=5)
INFO     Training for 5 epochs.
INFO:scvi.model._scanvi:Training for 5 epochs.
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Set SLURM handle signals.
Epoch 1/5:   0%|                                           | 0/5 [00:00<?, ?it/s]/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/distributions/_negative_binomial.py:436: UserWarning: The value argument must be within the support of the distribution
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/model/_scanvi.py", line 398, in train
    return runner()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/train/_trainrunner.py", line 74, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 740, in fit
    self._call_and_handle_interrupt(
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
    self._results = trainer.run_stage()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1289, in run_stage
    return self._run_train()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1319, in _run_train
    self.fit_loop.run()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
    self.epoch_loop.run(data_fetcher)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 193, in advance
    batch_output = self.batch_loop.run(batch, batch_idx)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(split_batch, optimizers, batch_idx)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 215, in advance
    result = self._run_optimization(
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 266, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 378, in _optimizer_step
    lightning_module.optimizer_step(
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/core/lightning.py", line 1652, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/core/optimizer.py", line 164, in step
    trainer.accelerator.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 339, in optimizer_step
    self.precision_plugin.optimizer_step(model, optimizer, opt_idx, closure, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 163, in optimizer_step
    optimizer.step(closure=closure, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/optim/optimizer.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/optim/adam.py", line 100, in step
    loss = closure()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/plugins/precision/precision_plugin.py", line 148, in _wrap_closure
    closure_result = closure()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 160, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 142, in closure
    step_output = self._step_fn()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 435, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 219, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 213, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/train/_trainingplans.py", line 595, in training_step
    _, _, scvi_losses = self.forward(full_dataset, loss_kwargs=input_kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/train/_trainingplans.py", line 187, in forward
    return self.module(*args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 162, in forward
    return _generic_forward(
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 507, in _generic_forward
    losses = module.loss(
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/_scanvae.py", line 314, in loss
    classifier_loss = self.classification_loss(labelled_tensors)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/_scanvae.py", line 214, in classification_loss
    self.classify(x, batch_idx), y.view(-1).long()
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/module/_scanvae.py", line 191, in classify
    qz_m, _, z = self.z_encoder(x, batch_index)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/nn/_base_components.py", line 293, in forward
    q = self.encoder(x, *cat_list)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/scvi/nn/_base_components.py", line 197, in forward
    x = layer(x)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mcgaugheyd/conda/envs/scvitools15/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (128x2013 and 2014x128)
```

# I figured it out!
If I remove the `continuous_covariate_keys = ['percent.mt']` in the `scvi.model.SCVI.setup_anndata` step...then it works. I guess the continuous covariate isn't being carried over and is the "off by one" error. Is this intentional or an oversight?

**Comment by adamgayoso** [comment]
Thanks for raising this! Turns out scANVI was not hooked up properly to work with extra covariates in the case where `encode_covariates=True`. We will fix this soon.

Generally I'm not quite sure all the code has been checked for how extra covariates will respond in the scArches scenario

**Comment by davemcg** [comment]
Yeah it may be safer in the short term to just refuse to run `scvi.model.SCANVI.from_scvi_model` and give an informative error.
