### ISSUE TITLE
SCVI model errors with NaN-filled tensor

### ISSUE THREAD

**Issue by bkmartinjr** [scverse/scvi-tools#2103]
Likely related to, or same bug as, #2099 

The following test case will often error out during the first epoch of training.  Dataset is large so I will pass offline to @martinkim0 

```python
import anndata
import scvi
import torch


# set scVI seed (and it still generates warning...)
scvi.settings.seed = 0

# when on a g5 instance, with TensorCores, torch requires that we specify desired precision.
torch.set_float32_matmul_precision("high")


adata = anndata.read_h5ad("mus_musculus.h5ad")
print("loaded")
scvi.model.SCVI.setup_anndata(adata, layer="counts", batch_key="batch")
model = scvi.model.SCVI(adata, n_layers=4, n_latent=50, n_hidden=1024, gene_likelihood="nb")
model.train(max_epochs=10, batch_size=2048, accelerator="gpu")
print("done")
```

```pytb
/home/bruce/scvi-tools/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
/home/bruce/scvi-tools/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
Global seed set to 0
loaded
/home/bruce/scvi-tools/scvi/data/fields/_dataframe_field.py:189: UserWarning: Category 99 in adata.obs['_scvi_batch'] has fewer than 3 cells. Models may not train properly.
  categorical_mapping = _make_column_categorical(
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]
Epoch 1/10:   0%|                                                                                                                                       | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/bruce/scvi/boom.py", line 17, in <module>
    model.train(max_epochs=10, batch_size=2048, accelerator="gpu")
  File "/home/bruce/scvi-tools/scvi/model/base/_training_mixin.py", line 91, in train
    return runner()
  File "/home/bruce/scvi-tools/scvi/train/_trainrunner.py", line 99, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/home/bruce/scvi-tools/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 260, in _optimizer_step
    call._call_lightning_module_hook(
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 140, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/core/module.py", line 1256, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/core/optimizer.py", line 155, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 225, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 114, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 280, in wrapper
    out = func(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 33, in _use_grad
    ret = func(self, *args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/optim/adam.py", line 121, in step
    loss = closure()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 101, in _wrap_closure
    closure_result = closure()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 307, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 287, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/lightning/pytorch/strategies/strategy.py", line 367, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/train/_trainingplans.py", line 342, in training_step
    _, _, scvi_loss = self.forward(batch, loss_kwargs=self.loss_kwargs)
  File "/home/bruce/scvi-tools/scvi/train/_trainingplans.py", line 278, in forward
    return self.module(*args, **kwargs)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/module/base/_base_module.py", line 199, in forward
    return _generic_forward(
  File "/home/bruce/scvi-tools/scvi/module/base/_base_module.py", line 743, in _generic_forward
    inference_outputs = module.inference(**inference_inputs, **inference_kwargs)
  File "/home/bruce/scvi-tools/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/module/base/_base_module.py", line 303, in inference
    return self._regular_inference(*args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/module/_vae.py", line 336, in _regular_inference
    qz, z = self.z_encoder(encoder_input, batch_index, *categorical_input)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/bruce/scvi-tools/scvi/nn/_base_components.py", line 289, in forward
    dist = Normal(q_m, q_v.sqrt())
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/distributions/normal.py", line 56, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/home/bruce/scvi/venv/lib/python3.10/site-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (2048, 50)) of distribution Normal(loc: torch.Size([2048, 50]), scale: torch.Size([2048, 50])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        ...,
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
Epoch 1/10:   0%|                                                                                                                                       | 0/10 [00:03<?, ?it/s]```

#### Versions:

SCVI 1.0.0
Ubuntu 22
Python 3.10
CUDA 0.11.8

**Comment by martinkim0** [comment]
Looks like this is erroring out due to the exponential activation we have on the latent variance. Replacing it with a ReLU seems to address it, at least for this dataset. Need to test out whether this is an issue for this particular model configuration or a more general issue.

**Comment by martinkim0** [comment]
Probably similar to #1903 @adamgayoso? Looks like the exponential activation leads to numerical instability in other parts of the code

**Comment by Nh-code** [comment]
> Looks like this is erroring out due to the exponential activation we have on the latent variance. Replacing it with a ReLU seems to address it, at least for this dataset. Need to test out whether this is an issue for this particular model configuration or a more general issue.

I have a similar problem with `st_model.train(max_epochs=2500)`, can you show me how to simply set the ReLU activation?

**Comment by cane11** [comment]
ReLU is not recommended here. We don't want zero variances. Your error looks like a problem with destVI. Can you open a new bug and highlight the version of the code, the exact error message, and additionally for this case min_counts per cell after filtering to common genes and the exact combination of which single-cell technology and which spatial technology?

**Comment by Nh-code** [comment]
> 

#### version:
```
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
scanpy                        1.9.3
scvi-colab                    0.12.0
scvi-tools                    1.0.0
```

#### min_counts per spatial cell
```
>>> st_adata.obs['nCount_Spatial'].describe()
count    13346.000000
mean       172.240372
std        221.901825
min          1.000000
25%         46.000000
50%         99.000000
75%        199.000000
max       3128.000000
Name: nCount_Spatial, dtype: float64
```
#### min_counts per scrna cell
```
>>> sc_adata.obs['nCount_RNA'].describe()
count    14717.000000
mean      5961.724400
std       4110.445616
min        651.000000
25%       2990.000000
50%       4973.000000
75%       7780.000000
max      42781.000000
Name: nCount_RNA, dtype: float64
```

#### Script 
```
import numpy as np
import scanpy as sc
import diopy,h5py
import pandas as pd
import os,sys,csv,re
from scvi.model import CondSCVI, DestVI

tag = str(sys.argv[1])

### 1\ LOAD scrna
h5 = h5py.File('../sc_ref//seu.downsample_5k.h5', 'r')
sc_adata = diopy.input.h5_to_adata(h5 = h5, assay_name='RNA')
h5.close()
sc_adata.raw = sc_adata

### 2\ LOAD strna
h5 = h5py.File('../st_qry//'+tag+'.cla.h5', 'r')
st_adata = diopy.input.h5_to_adata(h5 = h5, assay_name='Spatial')
h5.close()
st_adata.raw = st_adata
st_adata.obsm["spatial"] = st_adata.obs[['x','y']].to_numpy(dtype = 'f') ### add spatial embedding

### filter genes to be the same on the spatial data & scrna data
with open('../sc_ref/sc.dw_hvgs.txt', 'r') as f:
    sc_hvgs = [line.strip() for line in f.readlines()] 
with open('../st_qry//'+tag+'.clahvgs.txt', 'r') as f:
    st_hvgs = [line.strip() for line in f.readlines()]

unions = np.union1d(sc_hvgs,st_hvgs)
intersect = list(set(unions).intersection(sc_adata.var_names,st_adata.var_names))
st_adata = st_adata[:, intersect].copy()
sc_adata = sc_adata[:, intersect].copy()

#### 3.1\ Train sc_model
CondSCVI.setup_anndata(sc_adata, layer="counts", labels_key="Subclass")
sc_model = CondSCVI(sc_adata, weight_obs=False)
sc_model.train()
#### 3.2\ Train st_model
DestVI.setup_anndata(st_adata, layer="counts")
st_model = DestVI.from_rna_model(st_adata, sc_model)
st_model.train(max_epochs=2000)
```

#### Error Info
```
  rank_zero_warn(
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/fabric/plugins/environments/slurm.py:165: PossibleUserWarning: The `srun` command is available on your system but is not used. HINT: If your intention is to run Lightning on SLURM, prepend your python command with `srun` like so: srun python scvi_dt.py st_T29 ...
  rank_zero_warn(

Epoch 1/2000:   0%|          | 0/2000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/path/zhuzhiyong/sp_maca.cla/destvi_0627/transfer_2/scvi_dt.py", line 50, in <module>
    st_model.train(max_epochs=2000)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/model/_destvi.py", line 362, in train
    super().train(
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/model/base/_training_mixin.py", line 88, in train
    return runner()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/train/_trainrunner.py", line 99, in __call__
    self.trainer.fit(self.training_plan, self.data_splitter)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/train/_trainer.py", line 186, in fit
    super().fit(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 218, in advance
    batch_output = self.automatic_optimization.run(trainer.optimizers[0], kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 185, in run
    self._optimizer_step(kwargs.get("batch_idx", 0), closure)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 260, in _optimizer_step
    call._call_lightning_module_hook(
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 140, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1256, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/core/optimizer.py", line 155, in step
    step_output = self._strategy.optimizer_step(self._optimizer, closure, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 225, in optimizer_step
    return self.precision_plugin.optimizer_step(optimizer, model=model, closure=closure, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 114, in optimizer_step
    return optimizer.step(closure=closure, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/optim/optimizer.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/optim/adam.py", line 118, in step
    loss = closure()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/plugins/precision/precision_plugin.py", line 101, in _wrap_closure
    closure_result = closure()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 140, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 126, in closure
    step_output = self._step_fn()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/automatic.py", line 307, in _training_step
    training_step_output = call._call_strategy_hook(trainer, "training_step", *kwargs.values())
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 287, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/lightning/pytorch/strategies/strategy.py", line 367, in training_step
    return self.model.training_step(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/train/_trainingplans.py", line 342, in training_step
    _, _, scvi_loss = self.forward(batch, loss_kwargs=self.loss_kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/train/_trainingplans.py", line 278, in forward
    return self.module(*args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/module/base/_decorators.py", line 32, in auto_transfer_args
    return fn(self, *args, **kwargs)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 199, in forward
    return _generic_forward(
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 749, in _generic_forward
    losses = module.loss(
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/scvi/module/_mrdeconv.py", line 282, in loss
    -self.eta_reg * Normal(mean, scale).log_prob(self.eta).sum()
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/distributions/normal.py", line 77, in log_prob
    self._validate_sample(value)
  File "/path/anaconda3/envs/zzy_scrna/lib/python3.9/site-packages/torch/distributions/distribution.py", line 293, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Parameter of shape (3326,)) to be within the support (Real()) of the distribution Normal(loc: torch.Size([3326]), scale: torch.Size([3326])), but found invalid values:
Parameter containing:
tensor([nan, nan, nan,  ..., nan, nan, nan], requires_grad=True)
Epoch 1/2000:   0%|          | 0/2000 [00:01<?, ?it/s]
```

**Comment by cane11** [comment]
Thanks for providing this example. You should check for spots outside of the tissue or with extremely low capture and filter counts in st_adata to definitely >100 counts (most likely from the quantile 1000 should be fine). You can't deconvolve a spot with only 1 count. I am more permissive in filtering in spatial data and do it while looking at spatial distribution. I expect your NaN issues to disappear than.
@martinkim0: It's interesting though as self.eps is only fed into a softplus function and no exponential function https://github.com/scverse/scvi-tools/blob/6b237f4411358cc156d191705c54f3d432c44e0b/scvi/module/_mrdeconv.py#L208. I guess we will not get rid of those NaN issues also at other parts of the code and reasonable preprocessing is important, even though use of Softplus will make the optimization more stable.

**Comment by martinkim0** [comment]
Yes we should leave in the exponential activation for backwards compatibility, although we should make it clear somewhere in our documentation that this could be the source of NaN bugs. 

It's interesting to note that @bkmartinjr 's code example does not fail if you remove any of the custom parameters in the model definition
```
model = scvi.model.SCVI(adata, n_layers=4, n_latent=50, n_hidden=1024, gene_likelihood="nb")
```
Removing any one of `n_layers=4, n_latent=50, n_hidden=1024, gene_likelihood="nb"` leads to normal training.

**Comment by Nh-code** [comment]
> Thanks for providing this example. You should check for spots outside of the tissue or with extremely low capture and filter counts in st_adata to definitely >100 counts (most likely from the quantile 1000 should be fine). You can't deconvolve a spot with only 1 count. I am more permissive in filtering spatial data and do it while looking at spatial distribution. I expect your NaN issues to disappear then. @martinkim0: It's interesting though as self.eps is only fed into a softplus function and no exponential function
> 
> https://github.com/scverse/scvi-tools/blob/6b237f4411358cc156d191705c54f3d432c44e0b/scvi/module/_mrdeconv.py#L208
> 
> . I guess we will not get rid of those NaN issues also at other parts of the code and reasonable preprocessing is important, even though use of Softplus will make the optimization more stable.

I tried filter nfeatures > 100 and it seems to work.
