### ISSUE TITLE
Finding errors when following the SCVI-tools cellassign tutorial.

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scvi-tools#2133]
Bug happens when I load in your sce_follicular_annotated_final file as a h5ad. I downloaded the files onto my computer from the google drive links in the tutorial and loaded them in. When trying to do obs_names_make_unique() and var_names_make_unique() I get the error.

```python
adata = sc.read("data/sce_follicular_annotated_final.h5ad")
marker_gene_mat = pd.read_csv('data/FL_celltype.csv', index_col=0)
adata.obs_names_make_unique()
adata.var_names_make_unique()
```

```pytb
Traceback (most recent call last):
  File "C:\Users\zacha\PycharmProjects\choroid\pipeline.py", line 14, in <module>
    adata.obs_names_make_unique()
  File "C:\Users\zacha\.conda\envs\choroid\lib\site-packages\anndata\_core\anndata.py", line 1824, in obs_names_make_unique
    self.obs_names = utils.make_index_unique(self.obs.index, join)
  File "C:\Users\zacha\.conda\envs\choroid\lib\site-packages\anndata\utils.py", line 213, in make_index_unique
    values_dup[i] = tentative_new_name
  File "C:\Users\zacha\.conda\envs\choroid\lib\site-packages\pandas\core\arrays\_mixins.py", line 249, in __setitem__
    value = self._validate_setitem_value(value)
  File "C:\Users\zacha\.conda\envs\choroid\lib\site-packages\pandas\core\arrays\categorical.py", line 1297, in _validate_setitem_value
    return self._validate_scalar(value)
  File "C:\Users\zacha\.conda\envs\choroid\lib\site-packages\pandas\core\arrays\categorical.py", line 1322, in _validate_scalar
    raise TypeError(
TypeError: Cannot setitem on a Categorical with a new category (AACTCAGAGCCTCGTG-1-1), set the categories first
```

#### Versions:

1.0.0
> VERSION

**Comment by cane11** [comment]
Hi,
It's most likely a problem with typecasting in newer versions of Scanpy. We will have a look and update the tutorial. A quick fix is most likely to explicitly convert the index to a string: `adata.obs.index = adata.obs.index.astype('str')`.
Thanks for reporting the problem.
