### ISSUE TITLE
Issue converting scanpy back to seurat

### ISSUE THREAD

**Issue by zacharyjxy2020** [scverse/scvi-tools#2196]
I try to use the write function of anndata to write my scanpy object to be read into my seurat in Rstudio. I get an error when I use this function. I am trying to transfer my anndata which has been clustered and processed through CellAssign to Seurat while maintaining cluster labels.

```python
import matplotlib.pyplot as plt
import pandas as pd
import scanpy as sc
import seaborn as sns
import numpy as np
import scvi
from scvi.external import CellAssign

adata = sc.read("data/choroid.h5ad")
adata.obs.index = adata.obs.index.astype('str')
adata.var.index = adata.var.index.astype('str')
marker_gene_mat = pd.read_csv('data/markerMatrixMouseChoroid.csv', index_col=0)
adata.obs_names_make_unique()
adata.var_names_make_unique()
print(marker_gene_mat)

adata_genes = adata.var_names
marker_gene_df = pd.DataFrame(marker_gene_mat)
filtered_marker_gene_df = marker_gene_df.loc[marker_gene_df.index.isin(adata_genes)]
print(filtered_marker_gene_df)


bdata = adata[:, filtered_marker_gene_df.index].copy()
lib_size = adata.X.sum(1)
bdata.obs['size_factor'] = lib_size/np.mean(lib_size)
scvi.external.CellAssign.setup_anndata(bdata, size_factor_key="size_factor")
model = CellAssign(bdata, filtered_marker_gene_df)
model.train()

model.history["elbo_validation"].plot()
predictions = model.predict()
predictions.to_csv('predictions.csv', index=True)

figure = sns.clustermap(predictions,cmap='viridis')
figure.savefig('clustermap.png')

sc.pp.normalize_total(bdata,target_sum=1e4)
sc.pp.log1p(bdata)
sc.pp.highly_variable_genes(bdata, min_mean=0.0125, max_mean=3, min_disp=0.5)
bdata_filtered = bdata[:, bdata.var.highly_variable]
sc.pp.scale(bdata_filtered, max_value=10)
sc.tl.pca(bdata_filtered, svd_solver='arpack')

sc.pp.neighbors(bdata_filtered, n_neighbors=10, n_pcs=40)
sc.tl.umap(bdata_filtered)

bdata_filtered.obs["scvi-tools predictions"] = predictions.idxmax(axis=1).values
sc.pl.umap(bdata_filtered, color=["scvi-tools predictions"], frameon=False, ncols=1, save=True)
sc.write('bdata_filtered.h5ad', bdata_filtered)

```

```pytb
Traceback (most recent call last):
  File "/home/yjx717/.local/lib/python3.11/site-packages/anndata/_io/utils.py", line 246, in func_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yjx717/.local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 311, in write_elem
    return write_func(store, k, elem, dataset_kwargs=dataset_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yjx717/.local/lib/python3.11/site-packages/anndata/_io/specs/registry.py", line 52, in wrapper
    result = func(g, k, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yjx717/.local/lib/python3.11/site-packages/anndata/_io/specs/methods.py", line 560, in write_dataframe
    raise ValueError(f"{reserved!r} is a reserved name for dataframe columns.")
ValueError: '_index' is a reserved name for dataframe columns.
```

#### Versions:

1.0.0

**Comment by martinkim0** [comment]
The following issue looks relevant: https://github.com/theislab/scvelo/issues/255

**Comment by zacharyjxy2020** [comment]
Ok great thanks!
