### ISSUE TITLE
scvi.model.SCVI.train() on GPU with multiple devices error: object of type numpy.int64 has no len()

### ISSUE THREAD

**Issue by MaximilianNuber** [scverse/scvi-tools#2236]
Hello everyone,

I am trying to train an scVI model on a celltype subset of my data and speed up the process by using the GPU. I created a new conda environment and followed installing procedures on the scVI-tools website for scVI, pytorch and jax.

Then i preprocessed the anndata and created and trained the model.

Using CPU or only one GPU (with "devices = auto | 1") the model trains as usual.

When i set the number of devices to more then one, I get [TypeError: object of type numpy.int64 has no len()]

I tried to follow the Differential Expression Tutorial on C. Elegans.

```python
import anndata as ad
adata = ad.AnnData(
    X = original.layers["counts"].copy(),
    obs = original.obs.copy(),
    var = original.var.copy()
)

adata.layers["counts"] = adata.X.copy()

sc.pp.normalize_total(adata)
sc.pp.log1p(adata)
adata.layers["normalized"] = adata.X.copy()
adata.raw = adata

sc.pp.highly_variable_genes(
    adata,
    flavor="seurat_v3",
    n_top_genes=3000,
    layer="counts",
    batch_key="dataset",
    subset=False,
)

sc.pp.pca(adata)
sc.pp.neighbors(adata, n_neighbors=10, n_pcs=30)
sc.tl.umap(adata)

adata_scvi = adata[:, adata.var["highly_variable"]].copy()

scvi.model.SCVI.setup_anndata(adata_scvi, layer="counts", batch_key="dataset")
model = scvi.model.SCVI(adata_scvi, gene_likelihood="nb")
max_epochs_scvi = 400

model.train(
    check_val_every_n_epoch=1,
    max_epochs=max_epochs_scvi,
    early_stopping=True,
    early_stopping_patience=20,
    early_stopping_monitor="elbo_validation",
    accelerator = "gpu",
    devices = 5
)

```

ProcessRaisedException                    Traceback (most recent call last)
Cell In[16], line 1
----> 1 model.train(
      2     check_val_every_n_epoch=1,
      3     max_epochs=max_epochs_scvi,
      4     early_stopping=True,
      5     early_stopping_patience=20,
      6     early_stopping_monitor="elbo_validation",
      7     accelerator = "gpu",
      8     devices = 5
      9 )

File ~/.local/lib/python3.10/site-packages/scvi/model/base/_training_mixin.py:88, in UnsupervisedTrainingMixin.train(self, max_epochs, use_gpu, accelerator, devices, train_size, validation_size, shuffle_set_split, batch_size, early_stopping, plan_kwargs, **trainer_kwargs)
     75 trainer_kwargs[es] = (
     76     early_stopping if es not in trainer_kwargs.keys() else trainer_kwargs[es]
     77 )
     78 runner = self._train_runner_cls(
     79     self,
     80     training_plan=training_plan,
   (...)
     86     **trainer_kwargs,
     87 )
---> 88 return runner()

File ~/.local/lib/python3.10/site-packages/scvi/train/_trainrunner.py:99, in TrainRunner.__call__(self)
     96 if hasattr(self.data_splitter, "n_val"):
     97     self.training_plan.n_obs_validation = self.data_splitter.n_val
---> 99 self.trainer.fit(self.training_plan, self.data_splitter)
    100 self._update_history()
    102 # data splitter only gets these attrs after fit

File ~/.local/lib/python3.10/site-packages/scvi/train/_trainer.py:186, in Trainer.fit(self, *args, **kwargs)
    180 if isinstance(args[0], PyroTrainingPlan):
    181     warnings.filterwarnings(
    182         action="ignore",
    183         category=UserWarning,
    184         message="`LightningModule.configure_optimizers` returned `None`",
    185     )
--> 186 super().fit(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py:529, in Trainer.fit(self, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path)
    527 model = _maybe_unwrap_optimized(model)
    528 self.strategy._lightning_module = model
--> 529 call._call_and_handle_interrupt(
    530     self, self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
    531 )

File ~/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py:41, in _call_and_handle_interrupt(trainer, trainer_fn, *args, **kwargs)
     39 try:
     40     if trainer.strategy.launcher is not None:
---> 41         return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
     42     return trainer_fn(*args, **kwargs)
     44 except _TunerExitException:

File ~/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py:124, in _MultiProcessingLauncher.launch(self, function, trainer, *args, **kwargs)
    116 process_context = mp.start_processes(
    117     self._wrapping_function,
    118     args=process_args,
   (...)
    121     join=False,  # we will join ourselves to get the process references
    122 )
    123 self.procs = process_context.processes
--> 124 while not process_context.join():
    125     pass
    127 worker_output = return_queue.get()

File ~/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py:160, in ProcessContext.join(self, timeout)
    158 msg = "\n\n-- Process %d terminated with the following error:\n" % error_index
    159 msg += original_trace
--> 160 raise ProcessRaisedException(msg, error_index, failed_process.pid)

ProcessRaisedException: 

-- Process 4 terminated with the following error:
Traceback (most recent call last):
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py", line 147, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 189, in advance
    batch = next(data_fetcher)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/loops/fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 284, in __next__
    out = next(self._iterator)
  File "/home/maxnuber/.local/lib/python3.10/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
    out[i] = next(self.iterators[i])
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/maxnuber/.local/lib/python3.10/site-packages/torch/utils/data/dataset.py", line 298, in __getitem__
    return self.dataset[self.indices[idx]]
  File "/home/maxnuber/.local/lib/python3.10/site-packages/scvi/data/_anntorchdataset.py", line 147, in __getitem__
    if isinstance(idx, int) or len(idx) == 1:
TypeError: object of type 'numpy.int64' has no len()

```pytb
[Paste the error output produced by the above code here]
```

#### Versions:

< '1.0.2' >

> VERSION

**Comment by MaximilianNuber** [comment]
I tried with 
accelerator = "cpu",
devices = 2
or more than 2 devices.
This reproduced the same error.

**Comment by martinkim0** [comment]
Hi, thanks for raising this issue. Please note that multi-GPU training is not supported in 1.0.2, but will be in 1.1.0 (the next release).

**Comment by MaximilianNuber** [comment]
I am so sorry, I did not find that.
But thank you for the reply.
