### ISSUE TITLE
Support for upcoming AnnData 0.10.0rc1 for compatibility with the latest rapids_singlecell

### ISSUE THREAD

**Issue by ktravaglini** [scverse/scvi-tools#2268]
Hello,

I recently tried setting up a new environment with the latest version of [rapids_singlecell](https://github.com/scverse/rapids_singlecell) (0.9.0, which pulls AnnData 0.10.0rc1) and scvi, I receive the error below while importing scvi.

Steps to reproduce:

environment.yml file
```
name: rapids-test
channels:
 - conda-forge
 - bioconda
 - rapidsai
 - nvidia
dependencies:
 - rapids=23.08
 - python=3.10
 - cuda-version=11.8
 - leidenalg
 - louvain
 - fa2
 - jupyterlab
 - pip
 - pip:
    - scvi-tools
    - scanpy
    - rapids_singlecell
```

Construct environment
`$ conda env create -f environment.yml `

Import scvi in the environment
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scvi
/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/_settings.py:63: UserWarning: Since v1.0.0, scvi-tools no longer uses a random seed by default. Run `scvi.settings.seed = 0` to reproduce results from previous versions.
  self.seed = seed
/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/_settings.py:70: UserWarning: Setting `dl_pin_memory_gpu_training` is deprecated in v1.0 and will be removed in v1.1. Please pass in `pin_memory` to the data loaders instead.
  self.dl_pin_memory_gpu_training = (
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/__init__.py", line 11, in <module>
    from . import autotune, data, model, external, utils, criticism
  File "/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/autotune/__init__.py", line 1, in <module>
    from ._manager import TuneAnalysis, TunerManager
  File "/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/autotune/_manager.py", line 23, in <module>
    from scvi.data._constants import _SETUP_ARGS_KEY, _SETUP_METHOD_NAME
  File "/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/data/__init__.py", line 3, in <module>
    from ._anntorchdataset import AnnTorchDataset
  File "/allen/programs/celltypes/workgroups/hct/ktrav/conda/envs/rapids-test/lib/python3.10/site-packages/scvi/data/_anntorchdataset.py", line 7, in <module>
    from anndata._core.sparse_dataset import SparseDataset
ImportError: cannot import name 'SparseDataset'
```
PR for new AnnData rc: https://github.com/scverse/anndata/pull/1066

This makes sense as "SparseDataset" was renamed in the RC, per https://github.com/scverse/anndata/commit/8c00a29d7b983e6be7bf437305133b422ffe8168

Want to check you're aware of the future conflict/ask if you know when you'll be able to support the new AnnData version?

Best,
Kyle

**Comment by martinkim0** [comment]
Hi, thanks for bringing up this issue. We're aware of the future conflict and are planning on supporting the new AnnData version. No specific timeline on this but we'll most likely add the changes for our v1.1 release coming up soon. If you feel comfortable, feel free to also put a PR in with a fix.
