### ISSUE TITLE
SCVI can no longer be imported in R studio via reticulate

### ISSUE THREAD

**Issue by CCCC1800** [scverse/scvi-tools#2694]
Hi,

I was using SCVI in R studio via reticulate (as shown in https://docs.scvi-tools.org/en/1.0.1/tutorials/notebooks/scvi_in_R.html). It didn't show bugs until recently, when I tried again, the SCVI can no longer be imported in R via reticulate. Except SCVI, other python packages I used can be imported in R as usual, so I guess this is a bug relating to SCVI itself.

Thank you

```python
##In R studio:
library(reticulate)
sc <- import('scanpy', convert = FALSE)
scvi <- import('scvi', convert = FALSE)
```

```pytb
Error in py_module_import(module, convert = convert) : AssertionError
Run `reticulate::py_last_error()` for details.
> reticulate::py_last_error()

── Python Exception Message ─────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/__init__.py", line 10, in <module>
    from . import data, model, external
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/model/__init__.py", line 1, in <module>
    from ._autozi import AUTOZI
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/model/_autozi.py", line 12, in <module>
    from scvi.model.base import UnsupervisedTrainingMixin
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/model/base/__init__.py", line 1, in <module>
    from ._archesmixin import ArchesMixin
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/model/base/_archesmixin.py", line 13, in <module>
    from ._base_model import BaseModelClass
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/scvi/model/base/_base_model.py", line 10, in <module>
    import pyro
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/__init__.py", line 4, in <module>
    import pyro.poutine as poutine
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/poutine/__init__.py", line 4, in <module>
    from .handlers import (
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/poutine/handlers.py", line 60, in <module>
    from .collapse_messenger import CollapseMessenger
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/poutine/collapse_messenger.py", line 7, in <module>
    from pyro.distributions.distribution import COERCIONS
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/distributions/__init__.py", line 4, in <module>
    import pyro.distributions.torch_patch  # noqa F403
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/R/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/home/ubuntu/chenlab_deeplearning/chenlab_deeplearning_V2/anaconda3/envs/SCANVI/lib/python3.9/site-packages/pyro/distributions/torch_patch.py", line 10, in <module>
    assert torch.__version__.startswith("1.")
AssertionError

── R Traceback ──────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─reticulate::import("scvi", convert = FALSE)
 2.   └─reticulate:::py_module_import(module, convert = convert)```

#### Versions:

<!-- Output of scvi.__version__ -->
R version: 4.1.1
Python version: 3.9.2

Versions of python packages:
scvi-tools: 0.12.1

Versions of R packages:
reticulate: 1.30

> VERSION

<!-- Relevant screenshots -->

**Comment by canergen** [comment]
Hi, can you confirm that you currently can't import pyro in your environment? `import pyro` is failing above. The issue is that your pyro version is old and requires pytorch<2.0. This is likely not the case. You will need to update pyro. How have you set up the environment?

**Comment by CCCC1800** [comment]
Thank you for pointing out. Yes after downgrading the PyTorch version the code can work again.
