### ISSUE TITLE
Issues in  Load Dataset with SeuratData and convert to adata

### ISSUE THREAD

**Issue by GischD** [scverse/scvi-tools#2815]
Dear scvi-tools team,
Thank you for all your hard work to keep the tool working well.
I have a script in R using the reticulate.
The script works for one Seurat object but not for another.
I try to inspect both objects, but I don't find any differences.

I appreciate your thoughts about what is causing the issue.

Best Regards,
Debora

```R

library(Seurat)
library(Signac)
library(SeuratDisk)
library(SeuratData)
library(Gviz)
library(GenomicRanges)
library(rtracklayer)
library(dplyr)
library(reticulate)
library(sceasy)
reticulate::virtualenv_list()
## Change the Path
Sys.setenv(RETICULATE_PYTHON="/home/.virtualenvs/r-reticulate_3p10/bin/python")
## Use the virtualenv
reticulate::use_virtualenv("r-reticulate_3p10")

  sc <- import("scanpy", convert = FALSE)
  scvi <- import("scvi", convert = FALSE) #chech if the sc
  i <- "S16.RDA"
  name <- "S16"
  load(i)
  DefaultAssay(obj) <- "RNA"
  adata <- convertFormat(obj, from="seurat", to="anndata", main_layer="counts",drop_single_values=FALSE,outFile = paste0(name,".h5ad"))

```

```pytb
── Python Exception Message ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_core/anndata.py", line 1929, in write_h5ad
    write_h5ad(
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/h5ad.py", line 104, in write_h5ad
    write_elem(f, "obs", adata.obs, dataset_kwargs=dataset_kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 359, in write_elem
    Writer(_REGISTRY).write_elem(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/utils.py", line 243, in func_wrapper
    return func(*args, **kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 309, in write_elem
    return write_func(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 57, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/methods.py", line 707, in write_dataframe
    _writer.write_elem(
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/utils.py", line 243, in func_wrapper
    return func(*args, **kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 309, in write_elem
    return write_func(store, k, elem, dataset_kwargs=dataset_kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/registry.py", line 57, in wrapper
    result = func(g, k, *args, **kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/anndata/_io/specs/methods.py", line 414, in write_vlen_string_array
    f.create_dataset(k, data=elem.astype(str_dtype), dtype=str_dtype, **dataset_kwargs)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/.virtualenvs/r-reticulate_3p10/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 166, in make_new_dset
    dset_id.write(h5s.ALL, h5s.ALL, data)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 282, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 147, in h5py._proxy.dset_rw
  File "h5py/_conv.pyx", line 442, in h5py._conv.str2vlen
  File "h5py/_conv.pyx", line 96, in h5py._conv.generic_converter
  File "h5py/_conv.pyx", line 247, in h5py._conv.conv_str2vlen
TypeError: Can't implicitly convert non-string objects to strings
Error raised while writing key 'v1_barcode' of <class 'h5py._hl.group.Group'> to /obs

── R Traceback ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    ▆
 1. └─sceasy::convertFormat(...)
 2.   └─sceasy (local) func(obj, outFile = outFile, main_layer = main_layer, ...) at cellgeni-sceasy-c1c0bf9/R/methods.R:29:3
 3.     └─adata$write(outFile, compression = "gzip") at cellgeni-sceasy-c1c0bf9/R/functions.R:96:5
 4.       └─reticulate:::py_call_impl(callable, call_args$unnamed, call_args$named) at reticulate/R/python.R:1182:5
See `reticulate::py_last_error()$r_trace$full_call` for more details.

reticulate::py_last_error()$r_trace$full_call
[[1]]
convertFormat(obj, from = "seurat", to = "anndata", main_layer = "counts", 
    drop_single_values = FALSE, outFile = paste0(output_folder, 
        name, ".h5ad"))

[[2]]
return(func(obj, outFile = outFile, main_layer = main_layer, ...))

[[3]]
adata$write(outFile, compression = "gzip")

[[4]]
result <- py_call_impl(callable, call_args$unnamed, call_args$named)


```

#### Versions:

> VERSION

R version 4.3.2 (2023-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats4    stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1] stringr_1.5.1               sceasy_0.0.7                reticulate_1.36.1           dplyr_1.1.4                 rtracklayer_1.60.1          cicero_1.3.9               
 [7] Gviz_1.44.2                 monocle3_1.3.7              SingleCellExperiment_1.22.0 SummarizedExperiment_1.30.2 GenomicRanges_1.52.1        GenomeInfoDb_1.36.4        
[13] IRanges_2.34.1              S4Vectors_0.38.2            MatrixGenerics_1.12.3       matrixStats_1.1.0           Biobase_2.60.0              BiocGenerics_0.46.0        
[19] SeuratData_0.2.2.9001       SeuratDisk_0.0.0.9021       Signac_1.12.0               Seurat_5.0.1                SeuratObject_5.0.1          sp_2.1-2                   

loaded via a namespace (and not attached):
  [1] ProtGenerics_1.32.0      spatstat.sparse_3.0-3    bitops_1.0-7             httr_1.4.7               RColorBrewer_1.1-3       tools_4.3.2              sctransform_0.4.1       
  [8] backports_1.4.1          utf8_1.2.4               R6_2.5.1                 lazyeval_0.2.2           uwot_0.1.16              withr_2.5.2              prettyunits_1.2.0       
 [15] gridExtra_2.3            progressr_0.14.0         cli_3.6.1                spatstat.explore_3.2-5   fastDummies_1.7.3        spatstat.data_3.0-3      ggridges_0.5.4          
 [22] pbapply_1.7-2            Rsamtools_2.16.0         foreign_0.8-86           dichromat_2.0-0.1        parallelly_1.36.0        BSgenome_1.68.0          VGAM_1.1-10             
 [29] rstudioapi_0.15.0        RSQLite_2.3.3            generics_0.1.3           BiocIO_1.10.0            ica_1.0-3                spatstat.random_3.2-2    interp_1.1-6            
 [36] Matrix_1.6-4             fansi_1.0.5              abind_1.4-5              lifecycle_1.0.4          yaml_2.3.7               BiocFileCache_2.8.0      Rtsne_0.16              
 [43] blob_1.2.4               promises_1.2.1           crayon_1.5.2             miniUI_0.1.1.1           lattice_0.22-5           cowplot_1.1.1            GenomicFeatures_1.52.2  
 [50] KEGGREST_1.40.1          pillar_1.9.0             knitr_1.45               rjson_0.2.21             boot_1.3-28              future.apply_1.11.0      codetools_0.2-19        
 [57] fastmatch_1.1-4          leiden_0.4.3.1           glue_1.6.2               data.table_1.14.8        vctrs_0.6.4              png_0.1-8                spam_2.10-0             
 [64] gtable_0.3.4             cachem_1.0.8             xfun_0.41                S4Arrays_1.0.6           mime_0.12                survival_3.5-7           RcppRoll_0.3.0          
 [71] ellipsis_0.3.2           fitdistrplus_1.1-11      ROCR_1.0-11              nlme_3.1-163             bit64_4.0.5              progress_1.2.2           filelock_1.0.2          
 [78] RcppAnnoy_0.0.21         irlba_2.3.5.1            KernSmooth_2.23-22       rpart_4.1.21             colorspace_2.1-0         DBI_1.1.3                Hmisc_5.1-1             
 [85] nnet_7.3-19              tidyselect_1.2.0         bit_4.0.5                compiler_4.3.2           curl_5.1.0               htmlTable_2.4.2          hdf5r_1.3.8             
 [92] xml2_1.3.6               DelayedArray_0.26.7      plotly_4.10.3            checkmate_2.3.1          scales_1.3.0             lmtest_0.9-40            rappdirs_0.3.3          
 [99] digest_0.6.33            goftest_1.2-3            spatstat.utils_3.0-4     minqa_1.2.6              rmarkdown_2.26           XVector_0.40.0           jpeg_0.1-10             
[106] htmltools_0.5.7          pkgconfig_2.0.3          base64enc_0.1-3          lme4_1.1-35.1            dbplyr_2.3.4             fastmap_1.1.1            ensembldb_2.24.1        
[113] rlang_1.1.3              htmlwidgets_1.6.3        shiny_1.8.0              zoo_1.8-12               jsonlite_1.8.7           BiocParallel_1.34.2      VariantAnnotation_1.46.0
[120] RCurl_1.98-1.13          magrittr_2.0.3           Formula_1.2-5            GenomeInfoDbData_1.2.10  dotCall64_1.1-1          patchwork_1.1.3          munsell_0.5.0           
[127] Rcpp_1.0.11              stringi_1.8.2            zlibbioc_1.46.0          MASS_7.3-60              plyr_1.8.9               parallel_4.3.2           listenv_0.9.0           
[134] ggrepel_0.9.4            deldir_2.0-2             Biostrings_2.68.1        splines_4.3.2            tensor_1.5               hms_1.1.3                igraph_1.5.1            
[141] spatstat.geom_3.2-7      RcppHNSW_0.5.0           reshape2_1.4.4           biomaRt_2.56.1           XML_3.99-0.16            evaluate_0.23            latticeExtra_0.6-30     
[148] biovizBase_1.48.0        renv_1.0.3               BiocManager_1.30.22      nloptr_2.0.3             httpuv_1.6.12            RANN_2.6.1               tidyr_1.3.0             
[155] purrr_1.0.2              polyclip_1.10-6          future_1.33.0            scattermore_1.2          ggplot2_3.4.4            xtable_1.8-4             restfulr_0.0.15         
[162] AnnotationFilter_1.24.0  RSpectra_0.16-1          later_1.3.1              viridisLite_0.4.2        tibble_3.2.1             memoise_2.0.1            AnnotationDbi_1.62.2    
[169] GenomicAlignments_1.36.0 cluster_2.1.5            globals_0.16.2

**Comment by canergen** [comment]
Hi, thanks for using scVI-tools. This is more a question to sceasy for converting Seurat to AnnData. So I’m closing here.
Your issue is: `Error raised while writing key 'v1_barcode' of <class 'h5py._hl.group.Group'> to /obs`. I assume there are Boolean or None values in this column of adata.obs. You can either change the values in this column to string or delete this column.

**Comment by GischD** [comment]
Thanks for the quick answer. 👍 
Works nicely!
