### ISSUE TITLE
Autotuning with Ray: DeprecationWarning: The `RunConfig(local_dir)` argument is deprecated. You should set the `RunConfig(storage_path)` instead.

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [scverse/scvi-tools#2895]
When trying to autotune a model, I get an deprecation error

Using this tutorial, but adjusted to my data:

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/tuning/autotune_scvi.html

```python
from scvi.autotune import ModelTuner
from ray import tune
from scvi import autotune

# os.environ["RAY_CHDIR_TO_TRIAL_DIR"] = "0"
# ray.init(runtime_env={"working_dir": "/mnt/work/RO_src/Pipelines/STAnalysis/notebooks/downstream/scRNA"})
# ray.shutdown()
# ray.init(log_to_driver=False)

sc.pp.filter_genes(adata_to_annotate, min_cells=50)

min_cells=25,
min_genes=200
log1p=True
use_raw=False
pct_counts_mt=25
qc_vars=["Mt", "Ribo", "Hb"]

# mitochondrial genes
adata_to_annotate.var["Mt"] = adata_to_annotate.var_names.str.startswith("MT-")
# ribosomal genes
adata_to_annotate.var["Ribo"] = adata_to_annotate.var_names.str.startswith(("RPS", "RPL"))
# hemoglobin genes.
adata_to_annotate.var["Hb"] = adata_to_annotate.var_names.str.contains(
    ("^HB[^(p)]")
)  # adata.var_names.str.contains('^Hb.*-')

sc.pp.calculate_qc_metrics(
    adata=adata_to_annotate,
    qc_vars=qc_vars,
    log1p=log1p,
    use_raw=use_raw,
    percent_top=[20],
    inplace=True,
)
model_cls = scvi.model.SCVI
model_cls.setup_anndata(
    adata_to_annotate,
    categorical_covariate_keys=["Sample"],
    continuous_covariate_keys=["pct_counts_Mt", "pct_counts_Ribo"],
)

tuner = ModelTuner(model_cls=model_cls)
tuner.info()

# Define search space of hyperparameters

search_space = {
    "n_hidden": tune.choice([92, 128, 196, 256]),
    "n_latent": tune.choice([10, 20, 30, 40, 50]),
    "n_layers": tune.choice([1, 2, 3]),
    "lr": tune.loguniform(lower=1e-6, upper=1e-2),
    "gene_likelihood": tune.choice(["nb", "zinb"]),
}

# Create tuner
results = tuner.fit(
    adata_to_annotate,
    metric="validation_loss",
    search_space=search_space,
    num_samples=100,
    max_epochs=20,

)


```
if I do the ray.init as the tutorial I get:

```


>>> ray.init(log_to_driver=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/worker.py", line 1681, in init
    ray_params,
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/node.py", line 333, in __init__
    if not connect_only:
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/node.py", line 1351, in start_head_processes
    f" GCS system config: {new_config}"
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/node.py", line 712, in get_gcs_client
    if self._gcs_client is None:
  File "/mnt/work/RO_src/venv/stnav_venv/lib/python3.10/site-packages/ray/_private/node.py", line 757, in _init_gcs_client
    self, suffix: str = "", prefix: str = "", directory_name: Optional[str] = None
RuntimeError: Failed to start GCS.  Last 0 lines of error files:

.Please check /mnt/scratch/tmp/ray/session_2024-07-12_14-45-47_283369_567844/logs/gcs_server.out for details


```
The log files are empty
#### Versions:

scvi-tools 1.1.5
ray 2.9.3

> VERSION

**Comment by Rafael-Silva-Oliveira** [comment]
> Thanks for the heads up! I've addressed the issue in #2831, which will be released in v1.2.

Perfect! Do we have a release date planned ahead for that version? Thanks
