### ISSUE TITLE
AttributeError: 'Poisson' object has no attribute 'mu' in POISSONVI get_accessibility_estimates

### ISSUE THREAD

**Issue by shahrozeabbas** [scverse/scvi-tools#3019]
Hello,

I am trying to generate "raw denoised" counts from a trained `POISSONVI` model. This is working for any value set for `library_size` except for when it is set to `latent`. 

My understanding is that the counts scaled to the `latent` library size should represent raw counts as much as possible and would like to sum these values for pseudobulk analysis. 

Here is my code used to generate the counts as well as the error:

```
model = scvi.external.poissonvi.POISSONVI.load(
    dir_path='models/atac/VC/', adata=adata, accelerator='gpu', device=1
)

adata.layers[counts_layer] = model.get_accessibility_estimates(
    adata=adata, n_samples=2, library_size='latent', return_mean=True,
)
```

Which produces:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abbass2/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/abbass2/.local/lib/python3.9/site-packages/scvi/external/poissonvi/_model.py", line 215, in get_accessibility_estimates
    accs = super().get_normalized_expression(
  File "/home/abbass2/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/abbass2/.local/lib/python3.9/site-packages/scvi/model/base/_rnamixin.py", line 268, in get_normalized_expression
    exp_ = getattr(generative_outputs["px"], generative_output_key)
AttributeError: 'Poisson' object has no attribute 'mu'
```

Thanks!

**Comment by canergen** [comment]
Hi, this should be fixed in scVI-tools 1.2.0.
However, it is not compatible with Python 3.9 anymore so you will need to update your environment. Please reopen if you still experience this issue.
