### ISSUE TITLE
Cateorical covariate setup

### ISSUE THREAD

**Issue by Hrovatin** [scverse/scvi-tools#3022]
IGNORE THIS, SEE 2nd COMMENT BELOW

Setting up SCVi with categorical covariates does not seem to work for me. I pulled `main` a few hours ago, working on my SysVI fork - but there are no changes introduced outside of "external" 

Minimal reproducibility example:
```
import scanpy as sc
import pandas as pd
import numpy as np
from scvi.model import SCVI

# Setup categorical

a=sc.AnnData(np.zeros((2,3)),obs=pd.DataFrame({'a':[1,2],'b':[3,4]}))

/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

SCVI.setup_anndata(a,batch_key='a',categorical_covariate_keys='b')

/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/fields/_dataframe_field.py:186: UserWarning: Category 0 in adata.obs['_scvi_batch'] has fewer than 3 cells. Models may not train properly.
  categorical_mapping = _make_column_categorical(
/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/fields/_dataframe_field.py:186: UserWarning: Category 0 in adata.obs['_scvi_labels'] has fewer than 3 cells. Models may not train properly.
  categorical_mapping = _make_column_categorical(
Traceback (most recent call last):
  File "/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-9ce6ae4efdc9>", line 1, in <module>
    SCVI.setup_anndata(a,batch_key='a',categorical_covariate_keys='b')
  File "/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/model/_scvi.py", line 232, in setup_anndata
    adata_manager.register_fields(adata, **kwargs)
  File "/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/_manager.py", line 186, in register_fields
    self._add_field(
  File "/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/_manager.py", line 229, in _add_field
    field_registry[_constants._STATE_REGISTRY_KEY] = field.register_field(adata)
  File "/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/fields/_arraylike_field.py", line 425, in register_field
    self._combine_fields(adata)
  File "/Users/karin.hrovatin/Documents/GitHub/scvi-tools-Hrovatin/src/scvi/data/fields/_arraylike_field.py", line 247, in _combine_fields
    attr[self.attr_key] = source[self.attr_keys].copy()
  File "/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 216, in __setitem__
    value = self._validate_value(value, key)
  File "/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 279, in _validate_value
    return super()._validate_value(val, key)
  File "/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 100, in _validate_value
    return coerce_array(val, name=name, allow_df=self._allow_df)
  File "/Users/karin.hrovatin/miniconda3/envs/scvi/lib/python3.10/site-packages/anndata/_core/storage.py", line 104, in coerce_array
    raise ValueError(msg) from e
ValueError: Obsm '_scvi_extra_categorical_covs' needs to be of one of np.ndarray, numpy.ma.core.MaskedArray, scipy.sparse.spmatrix, awkward.Array, h5py.Dataset, zarr.Array, zappy.base.ZappyArray, anndata.experimental.[CSC,CSR]Dataset, dask.array.Array, cupy.ndarray, or cupyx.scipy.sparse.spmatrix, not <class 'pandas.core.series.Series'>.


```

**Comment by Hrovatin** [comment]
I also tried installing a fresh scvi env via conda, as per install guide, but got bellow wee on scvi-tools import

```
>>> from scvi.model import SCVI

/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/flax/struct.py:132: FutureWarning: jax.tree_util.register_keypaths is deprecated, and will be removed in a future release. Please use `register_pytree_with_keys()` instead.
  jax.tree_util.register_keypaths(data_clz, keypaths)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/__init__.py", line 11, in <module>
    from . import data, model, external, utils
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/data/__init__.py", line 25, in <module>
    from ._preprocessing import (
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/data/_preprocessing.py", line 12, in <module>
    from scvi.model._utils import parse_device_args
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/model/__init__.py", line 2, in <module>
    from ._amortizedlda import AmortizedLDA
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/model/_amortizedlda.py", line 15, in <module>
    from scvi.module import AmortizedLDAPyroModule
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/module/__init__.py", line 1, in <module>
    from ._amortizedlda import AmortizedLDAPyroModule
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/module/_amortizedlda.py", line 15, in <module>
    from scvi.module.base import PyroBaseModuleClass, auto_move_data
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/module/base/__init__.py", line 1, in <module>
    from ._base_module import (
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/module/base/_base_module.py", line 14, in <module>
    from flax.training import train_state
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/flax/training/train_state.py", line 19, in <module>
    import optax
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/optax/__init__.py", line 18, in <module>
    from optax import losses
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/optax/losses/__init__.py", line 17, in <module>
    from optax.losses._classification import convex_kl_divergence
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/optax/losses/_classification.py", line 64, in <module>
    chex.warn_deprecated_function,
AttributeError: module 'chex' has no attribute 'warn_deprecated_function'

```

**Comment by Hrovatin** [comment]
Ok, the categorical one was just me being stupid and passing in a wrong input type - a conversion or more meaningful warning would be helpful. For continuous I still get an error.

```
>>> a=sc.AnnData(np.zeros((4,3)),obs=pd.DataFrame({'a':[1,2,11,22],'b':[3,4,33,44]}))
/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
>>> SCVI.setup_anndata(a,batch_key='a',categorical_covariate_keys=['b'])
/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/data/fields/_dataframe_field.py:186: UserWarning: Category 0 in adata.obs['_scvi_batch'] has fewer than 3 cells. Models may not train properly.
  categorical_mapping = _make_column_categorical(
/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/data/fields/_arraylike_field.py:410: UserWarning: Category 0 in adata.obs['b'] has fewer than 3 cells. Models may not train properly.
  mapping = _make_column_categorical(df, key, key, categorical_dtype=categorical_dtype)
>>> a=sc.AnnData(np.zeros((4,3)),obs=pd.DataFrame({'a':[1,2,11,22],'b':[3,4,33,44]}))
/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/anndata/_core/aligned_df.py:67: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
>>> SCVI.setup_anndata(a,batch_key='a',continous_covariate_keys=['b'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/model/_scvi.py", line 219, in setup_anndata
    adata_manager.register_fields(adata, **kwargs)
  File "/Users/karin.hrovatin/miniconda3/envs/scvi-test/lib/python3.9/site-packages/scvi/data/_manager.py", line 172, in register_fields
    raise TypeError(
TypeError: register_fields() got unexpected keyword arguments {'continous_covariate_keys': ['b']} passed without a source_registry.

```

**Comment by canergen** [comment]
The typing of the function is correct: categorical_covariate_keys: list[str]. This is also correctly rendered in the API documentation. It expects a list of strings. I don't like loose conversions as what is the conversion of "batch" one can argue that it's ["b", "a", "t", "c", "h"] or ["batch"]. Having a clear API and expecting input that aligns with this is much cleaner.

**Comment by Hrovatin** [comment]
@canergen Agree it is correct, but when I messed it up, I took me a while to figure it out since the error you get is way downstream. So maybe adding an error message if the passed object is not a list (or if it is a str/int) would be really useful.
